### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by ibugs961** [bmcorser/fontawesome-markdown#10]
```
pip install fontawesome-markdown
```
> Collecting fontawesome-markdown
  Using cached fontawesome-markdown-0.2.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxxxx\AppData\Local\Temp\pip-build-b5ybbcdx\fontawesome-markdown\setup.py", line 31, in <module>
        long_description=readme(),
      File "C:\Users\i_bugs\AppData\Local\Temp\pip-build-b5ybbcdx\fontawesome-markdown\setup.py", line 26, in readme
        return f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 639: illegal multibyte sequence

**Comment by ibugs961** [comment]
setup.py line28:
` with open('README.rst') as f:`   
-->
`with open('README.rst', encoding="utf-8") as f:`
